alias: Nursery Changing Table Button - Automations All
trigger:
  - device_id: ""
    domain: ""
    entity_id: ""
    platform: device
  - device_id: ""
    domain: ""
    entity_id: ""
    platform: device
  - device_id: ""
    domain: ""
    entity_id: ""
    platform: device
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - LongPress
        sequence:
          - service: media_player.turn_off
            data: {}
            target:
              entity_id: media_player.nursery_display
      - conditions:
          - condition: trigger
            id:
              - SinglePress
        sequence:
          - service: media_player.media_stop
            data: {}
            target:
              entity_id:
                - media_player.nursery_display
                - media_player.ytube_music_player_nursery
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 50
          - service: media_player.select_source
            data:
              source: media_player.nursery_display
            target:
              entity_id: media_player.ytube_music_player
            enabled: false
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 100
            enabled: false
          - service: media_player.volume_set
            data:
              volume_level: 0.4
            target:
              entity_id: media_player.nursery_display
          - service: media_player.play_media
            target:
              entity_id:
                - media_player.ytube_music_player_nursery
            data:
              media_content_id: PLnJkuSW5ixx5Mxx8DlCIJx-U08Qia9aZi
              media_content_type: channel
              enqueue: replace
          - service: media_player.shuffle_set
            data:
              shuffle: true
            target:
              entity_id:
                - media_player.ytube_music_player_nursery
      - conditions:
          - condition: trigger
            id:
              - DoublePress
        sequence:
          - service: media_player.media_stop
            data: {}
            target:
              entity_id:
                - media_player.nursery_display
                - media_player.ytube_music_player_nursery
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 50
          - service: media_player.select_source
            data:
              source: media_player.nursery_display
            target:
              entity_id: media_player.ytube_music_player
            enabled: false
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 100
            enabled: false
          - service: media_player.volume_set
            data:
              volume_level: 0.4
            target:
              entity_id: media_player.nursery_display
          - service: media_player.play_media
            target:
              entity_id:
                - media_player.ytube_music_player_nursery
            data:
              media_content_id: PLnJkuSW5ixx4r3_Q0G3_vJmmpcrgGcP6J
              media_content_type: channel
mode: parallel
